name: Deploy to production
on:
  push:
    branches: [ main ]

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with mina to VPS
        id: min-deploy
        uses: SlimGee/mina-action@main
        with:
          command: 'deploy'
          ssh_private_key: ${{ secrets.SSH_KEY }}
            
